
title: Sid Ag | Portfolio
email: agsid502@gmail.com
description: >-
  I am a software developer with a passion for creating innovative solutions. 
  With expertise in various programming languages and frameworks, 
  I enjoy tackling complex problems and delivering high-quality code.
  My portfolio showcases a range of projects that demonstrate my skills.

baseurl: "" 
url: "https://agsid.alliedalgos.org" 
github_username:  agsid

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag    
  - jekyll-sitemap  